### PR TITLE
tls_codec: feat: Add support for `Arbitrary` crate.

### PR DESCRIPTION
**Pull request by duesee**
This PR introduces an `arbitrary` feature that can be used to unlock `#[derive(Arbitrary)]` for `VLBytes` and `VLByteSlice`. The [`Arbitrary`](https://crates.io/crates/arbitrary) crate allows to create arbitrary instances of a struct that can be used, e.g., during fuzz-testing. I've also included a fuzz target to show how it works.

It is useful to have an `Arbitrary` implementation for `VLBytes` and `VLByteSlice` because `Arbitrary` can be automatically derived for structs/enums when all members implement `Arbitrary`. The reasons to provide support for `Arbitrary` in `tls_codec` pretty much align with the reasons to provide support for Serde in `tls_codec`.

Edit: I'm currently figuring out how to implement support for `TlsVecU8` etc. and should also limit the size for `VLBytes`.

### CODE REVIEW

**Comment by duesee** [comment]
I've converted this PR to a draft because CI is not happy. Should I put `--exclude-features arbitrary` here https://github.com/RustCrypto/formats/blob/master/.github/workflows/tls_codec.yml#L41?

**Comment by duesee** [comment]
I removed the `Arbitrary` derive for `VLByteSlice` and limited the length of `VLBytes` to `MAX_LEN`. So, this PR only adds `Arbitrary` support for `VLBytes` for now.

**Review by franziskuskiefer — APPROVED** [review]
Thanks, lgtm
Do you want to do this for the TLS vecs and other built-in types as well?

**Comment by duesee** [comment]
> Do you want to do this for the TLS vecs and other built-in types as well?

I think that `tls_codec` should have all these implementations, yes. But they require a bit more thought which is why I will take a look next year.

**Pull request merged**
