### PR TITLE
const-oid/v0.9.5 backporting rfc8410 OIDs

### PR DESCRIPTION
**Pull request by flihp**
backport rfc8410 OIDs into new release from const-oid/v0.9 branch following form from #1139

### CODE REVIEW

**Comment by flihp** [comment]
The workspace clippy check is failing here like it did in #1139: https://github.com/RustCrypto/formats/pull/1139#issuecomment-1629602079. I'm happy to help fix that up if necessary.

**Comment by tarcieri** [comment]
Looks like an MSRV-related failure. You can probably avoid it by running clippy without the `arbitrary` feature.

**Comment by baloo** [comment]
I also ignored the clippy error in #1139. Speaking personally, I'm fine with letting it fail.
If you're alright with that @tarcieri I'll merge that (bumping the date) and publish the release.

**Comment by flihp** [comment]
This PR has been updated with the workaround suggested by @tarcieri. I've also created a new issue to describe the root cause and make the info a bit more visible.

**Review by tarcieri — APPROVED** [review]

**Pull request merged**
