### PR TITLE
Enable dependabot for all subcrate in workspace

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by tarcieri** [comment]
I don't think this is necessary?

**Comment by NobodyXu** [comment]
> I don't think this is necessary?

Unfortunately it is, otherwise github dependabot won't check for new dependency in the subcrates/workspace, thus you won't be able to receive updates on new major releases in these subcrates.

**Comment by tarcieri** [comment]
> otherwise github dependabot won't check for new dependency in the subcrates/workspace

https://github.com/RustCrypto/formats/search?q=dependabot+chore%28deps%29&type=issues

**Comment by NobodyXu** [comment]
> > otherwise github dependabot won't check for new dependency in the subcrates/workspace
> 
> https://github.com/RustCrypto/formats/search?q=dependabot+chore%28deps%29&type=issues

Thanks, I didn't know that!
I checked the github doc and I didn't realize that it can do this for rust.

P.S. The link should be https://github.com/search?q=repo%3ARustCrypto%2Fformats+dependabot+chore%28deps%29&type=pullrequests

**Pull request closed without merging**
