### PR TITLE
Derive `Sequence` for more types

### PR DESCRIPTION
**Pull request by npmccallum**
This reduces the amount of custom code that is written.

Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

### CODE REVIEW

**Comment by tarcieri** [comment]
The `spki` crate is a deep, hard dependency of a number of different crates which don’t currently have any proc macro dependencies.

In cases like that, pulling in custom derive has a somewhat cost in terms of compile times of all of the proc macro dependencies, e.g. `syn`.

I’d prefer to keep `spki` proc macro-free at least, and probably `pkcs1` as well (`pkcs8` is another I’d prefer not to change).

`pkcs5` is a little more debatable, but also effectively “done” already.

The others are fine.

**Comment by carl-wallace** [comment]
Did I miss a change to derive? I am wondering what enables proper function with these manual mods gone.

**Comment by npmccallum** [comment]
@carl-wallace How does a developer run the aforementioned tests? And why aren't they in the CI?

**Comment by carl-wallace** [comment]
The bulk of the tests are in the certval library (and corresponding pittv3 tool) that let you build and validate certs live, enabling pretty thorough exercise of the encoders and decoders. The PR I submitted earlier this week (then chunked up a day or two ago) needs to clear for those first before certval and pittv3 are pushed. The quick test I did just now was to pull over these changes to the version used by certval/pittv3.

**Comment by npmccallum** [comment]
@carl-wallace Could you add those tests to this repo so that we can find breakage early?

**Comment by carl-wallace** [comment]
No, as the encoder/decoder that generates this is in the PR in front of it (and the bulk of the testing is driven by building and validating paths). Why is it vital to delete the manual impls now before those pieces land? That seems like the easiest path.

**Comment by npmccallum** [comment]
@carl-wallace I don't know which PR you're referring to. Could you provide a link?

**Comment by carl-wallace** [comment]
There was a large PR that you reviewed a few days ago that you suggested be chunked up. I chunked it up (but then pulled one piece back until these clear). One chunk has been processed. Two are currently outstanding: 356 and 357. Once those are done, a minor housekeeping PR will be pushed (to make cargo doc happier) then repos for certval/pittv3 can be set up (there's a yubikey mod that will follow those as well).

**Comment by npmccallum** [comment]
@carl-wallace Please note that if you add a hash (`#`) before the PR numbers, you get links directly to them. This aids readers of your comments. For example, the issues you are referring to are #356 and #357.

**Comment by carl-wallace** [comment]
FYI, there are some tests in #356 that should highlight breakage if you introduce your changes there. See the tests for trust_anchor_format. I did not try that specifically but what I did earlier is a close cousin to that action. Note, I think we will hit similar edges as CMS support emerges (I did not go enumerate where I think the issues will be but I think there will be similar cases).

**Comment by npmccallum** [comment]
@carl-wallace What I'm proposing is that if we can discover and fix these issues in the `derive` code, it makes all this later development easier. That means that each ASN.1 type that is added should have a test which governs it (either explicitly or implicitly). Otherwise, we have no way to know when things are broken or not.

**Comment by carl-wallace** [comment]
Is there macro change to enable the tests in #356 to pass? If not, please hold off on removing manual impls from x509 until the macros support tagging those structures.

**Pull request closed without merging**
