### PR TITLE
spki: replace `from_spki` with `TryFrom`

### PR DESCRIPTION
**Pull request by tarcieri**

### CODE REVIEW

**Comment by mzohreva** [comment]
A change to public API like this one requires bumping the minor version instead of releasing as a patch.

**Comment by tarcieri** [comment]
This was a breaking change to the v0.5.0 release, however that release was yanked.

Did this actually cause a real-world breakage in a program?

**Comment by mzohreva** [comment]
No breakage but a lot of confusion since I was seeing a different definition of the trait looking at docs.rs compared to what the compiler was claiming 🙂

**Comment by tarcieri** [comment]
If you were looking at the docs.rs for a yanked release, it should have a fairly prominent:

> ⚠️ This release has been yanked, go to latest version

...at the top of the page

**Comment by mzohreva** [comment]
True, but I was looking at this page: https://docs.rs/pkcs8/0.8.0/pkcs8/trait.DecodePublicKey.html (which is a re-export of the `spki` crate's public API)

**Comment by tarcieri** [comment]
Aah, I see...

**Pull request merged**
