### PR TITLE
feat(x509): add CRL type support

### PR DESCRIPTION
**Pull request by npmccallum**
This contains just the CRL portion of #462. I made sure to give @carl-wallace the author's credit.

One remaining question I have is why these are in the `crl` module. Are these types used in extensions? Or are they disconnected data types? If the latter, `crl` is probably the best place for them.

@tarcieri FYI

### CODE REVIEW

**Comment by carl-wallace** [comment]
I don't know what you mean by "these". The definitions in crl.rs are associated with crl processing. I will close #462 and keep eye on this repo and align higher level bits as this catches up.

**Comment by npmccallum** [comment]
@carl-wallace I mean the types in the `crl` module in this PR. Are the `crl` types used in extensions?

**Comment by carl-wallace** [comment]
No. There are only three structures: the primary CRL structure, its TBS structure and a structure fabricated from the revoked certs field of the TBS structure (as noted in the comment, for some reason the spec authors defined this structure inline). Feel free to split into smaller pieces if you prefer. Credit should probably go to Alan Smithee:-)

**Comment by npmccallum** [comment]
@carl-wallace Who would use these types and how are they used?

**Comment by carl-wallace** [comment]
See the comments in the code. https://datatracker.ietf.org/doc/html/rfc5280#section-5.1

**Comment by npmccallum** [comment]
@carl-wallace The standard defines the data types and what is hopes they accomplish from the perspective of 2008. It doesn't describe how these types are actually used in 2022. I'm hoping you can fill me in on the common usage patterns.

**Comment by carl-wallace** [comment]
these are fundamental structures. where crls are used, these are in play.

**Comment by tarcieri** [comment]
Thanks!

@carl-wallace hopefully this works for your use cases, or if not, feel free to open a PR to make adjustments

**Pull request merged**
