### PR TITLE
chore: remove non-pkix extensions

### PR DESCRIPTION
**Pull request by npmccallum**
The intent isn't to throw these away. But rather to resurrect them when:

1. Their OIDs are added to the OIDDB.
2. We know where to put them.

Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

### CODE REVIEW

**Comment by npmccallum** [comment]
@carl-wallace FYI

**Comment by carl-wallace** [comment]
OCSP no check is PKIX. Not sure why it landed in "other", but that's fine. As noted we "know where to put them".

**Comment by npmccallum** [comment]
@carl-wallace Because it isn't defined in RFC 5280 and I wasn't sure where to put it since I don't know what defines it.

**Comment by npmccallum** [comment]
@tarcieri I have more patches blocked on this.

**Comment by tarcieri** [comment]
I can merge this, but can you do a followup adding RFC6960 to oiddbgen?

**Pull request merged**
