### PR TITLE
Run tests using `cargo hack`

### PR DESCRIPTION
**Pull request by npmccallum**
This dynamically ensures that the various combinations of features flags
successfully work.

Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

### CODE REVIEW

**Comment by npmccallum** [comment]
Please note that this PR is intended to reveal existing breakage.

**Comment by franziskuskiefer** [comment]
Thanks @npmccallum 

The `no_std` support for `tls_codec` isn't really there yet (see #64). We can either disable default features on `serde` for `no_std` or not check for the `serde_serialize` feature on `no_std` platforms.

```
info: running `cargo build --release --target thumbv7em-none-eabi --no-default-features --features serde_serialize` on tls_codec (2/2)
   Compiling serde_derive v1.0.133
   Compiling serde v1.0.133
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabi` target may not support the standard library
  = note: `std` is required by `serde` because it does not declare `#![no_std]`
```

**Comment by npmccallum** [comment]
@franziskuskiefer I took a slightly different approach. Let me know if this doesn't work.

**Review by tarcieri — APPROVED** [review]

**Review by franziskuskiefer — APPROVED** [review]
> @franziskuskiefer I took a slightly different approach. Let me know if this doesn't work.

That works as well. Thanks!

**Pull request merged**
